using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WoWJunkyard.Views.ViewModels.ViewBags
{
    public class RealmList
    {
        public RealmList()
        {
            this.RealmNames = new List<SelectListItem>()
            {
                new SelectListItem {Text = "Aegwynn", Value = "Aegwynn"},
                new SelectListItem {Text = "Aerie Peak", Value = "Aerie Peak"},
                new SelectListItem {Text = "Agamaggan", Value = "Agamaggan"},
                new SelectListItem {Text = "Aggra", Value = "Aggra"},
                new SelectListItem {Text = "Aggramar", Value = "Aggramar"},
                new SelectListItem {Text = "Ahn'Qiraj", Value = "Ahn'Qiraj"},
                new SelectListItem {Text = "Al'Akir", Value = "Al'Akir"},
                new SelectListItem {Text = "Alexstrasza", Value = "Alexstrasza"},
                new SelectListItem {Text = "Alleria", Value = "Alleria"},
                new SelectListItem {Text = "Alonsus", Value = "Alonsus"},
                new SelectListItem {Text = "Aman'Thul", Value = "Aman'Thul"},
                new SelectListItem {Text = "Ambossar", Value = "Ambossar"},
                new SelectListItem {Text = "Anachronos", Value = "Anachronos"},
                new SelectListItem {Text = "Anetheron", Value = "Anetheron"},
                new SelectListItem {Text = "Antonidas", Value = "Antonidas"},
                new SelectListItem {Text = "Anub'arak", Value = "Anub'arak"},
                new SelectListItem {Text = "Arak-arahm", Value = "Arak-arahm"},
                new SelectListItem {Text = "Arathi", Value = "Arathi"},
                new SelectListItem {Text = "Arathor", Value = "Arathor"},
                new SelectListItem {Text = "Archimonde", Value = "Archimonde"},
                new SelectListItem {Text = "Area 52", Value = "Area 52"},
                new SelectListItem {Text = "Argent Dawn", Value = "Argent Dawn"},
                new SelectListItem {Text = "Arthas", Value = "Arthas"},
                new SelectListItem {Text = "Arygos", Value = "Arygos"},
                new SelectListItem {Text = "Ashenvale", Value = "Ashenvale"},
                new SelectListItem {Text = "Aszune", Value = "Aszune"},
                new SelectListItem {Text = "Auchindoun", Value = "Auchindoun"},
                new SelectListItem {Text = "Azjol-Nerub", Value = "Azjol-Nerub"},
                new SelectListItem {Text = "Azshara", Value = "Azshara"},
                new SelectListItem {Text = "Azuregos", Value = "Azuregos"},
                new SelectListItem {Text = "Azuremyst", Value = "Azuremyst"},
                new SelectListItem {Text = "Baelgun", Value = "Baelgun"},
                new SelectListItem {Text = "Balnazzar", Value = "Balnazzar"},
                new SelectListItem {Text = "Blackhand", Value = "Blackhand"},
                new SelectListItem {Text = "Blackmoore", Value = "Blackmoore"},
                new SelectListItem {Text = "Blackrock", Value = "Blackrock"},
                new SelectListItem {Text = "Blackscar", Value = "Blackscar"},
                new SelectListItem {Text = "Blade's Edge", Value = "Blade's Edge"},
                new SelectListItem {Text = "Bladefist", Value = "Bladefist"},
                new SelectListItem {Text = "Bloodfeather", Value = "Bloodfeather"},
                new SelectListItem {Text = "Bloodhoof", Value = "Bloodhoof"},
                new SelectListItem {Text = "Bloodscalp", Value = "Bloodscalp"},
                new SelectListItem {Text = "Blutkessel", Value = "Blutkessel"},
                new SelectListItem {Text = "Booty Bay", Value = "Booty Bay"},
                new SelectListItem {Text = "Borean Tundra", Value = "Borean Tundra"},
                new SelectListItem {Text = "Boulderfist", Value = "Boulderfist"},
                new SelectListItem {Text = "Bronze Dragonflight", Value = "Bronze Dragonflight"},
                new SelectListItem {Text = "Bronzebeard", Value = "Bronzebeard"},
                new SelectListItem {Text = "Burning Blade", Value = "Burning Blade"},
                new SelectListItem {Text = "Burning Legion", Value = "Burning Legion"},
                new SelectListItem {Text = "Burning Steppes", Value = "Burning Steppes"},
                new SelectListItem {Text = "C'Thun", Value = "C'Thun"},
                new SelectListItem {Text = "Chamber of Aspects", Value = "Chamber of Aspects"},
                new SelectListItem {Text = "Chants éternels", Value = "Chants éternels"},
                new SelectListItem {Text = "Cho'gall", Value = "Cho'gall"},
                new SelectListItem {Text = "Chromaggus", Value = "Chromaggus"},
                new SelectListItem {Text = "Colinas Pardas", Value = "Colinas Pardas"},
                new SelectListItem {Text = "Confrérie du Thorium", Value = "Confrérie du Thorium"},
                new SelectListItem {Text = "Conseil des Ombres", Value = "Conseil des Ombres"},
                new SelectListItem {Text = "Crushridge", Value = "Crushridge"},
                new SelectListItem {Text = "Culte de la Rive noire", Value = "Culte de la Rive noire"},
                new SelectListItem {Text = "Daggerspine", Value = "Daggerspine"},
                new SelectListItem {Text = "Dalaran", Value = "Dalaran"},
                new SelectListItem {Text = "Dalvengyr", Value = "Dalvengyr"},
                new SelectListItem {Text = "Darkmoon Faire", Value = "Darkmoon Faire"},
                new SelectListItem {Text = "Darksorrow", Value = "Darksorrow"},
                new SelectListItem {Text = "Darkspear", Value = "Darkspear"},
                new SelectListItem {Text = "Das Konsortium", Value = "Das Konsortium"},
                new SelectListItem {Text = "Das Syndikat", Value = "Das Syndikat"},
                new SelectListItem {Text = "Deathguard", Value = "Deathguard"},
                new SelectListItem {Text = "Deathweaver", Value = "Deathweaver"},
                new SelectListItem {Text = "Deathwing", Value = "Deathwing"},
                new SelectListItem {Text = "Deepholm", Value = "Deepholm"},
                new SelectListItem {Text = "Defias Brotherhood", Value = "Defias Brotherhood"},
                new SelectListItem {Text = "Dentarg", Value = "Dentarg"},
                new SelectListItem {Text = "Der Mithrilorden", Value = "Der Mithrilorden"},
                new SelectListItem {Text = "Der Rat von Dalaran", Value = "Der Rat von Dalaran"},
                new SelectListItem {Text = "Der abyssische Rat", Value = "Der abyssische Rat"},
                new SelectListItem {Text = "Destromath", Value = "Destromath"},
                new SelectListItem {Text = "Dethecus", Value = "Dethecus"},
                new SelectListItem {Text = "Die Aldor", Value = "Die Aldor"},
                new SelectListItem {Text = "Die Arguswacht", Value = "Die Arguswacht"},
                new SelectListItem {Text = "Die Nachtwache", Value = "Die Nachtwache"},
                new SelectListItem {Text = "Die Silberne Hand", Value = "Die Silberne Hand"},
                new SelectListItem {Text = "Die Todeskrallen", Value = "Die Todeskrallen"},
                new SelectListItem {Text = "Die ewige Wacht", Value = "Die ewige Wacht"},
                new SelectListItem {Text = "Doomhammer", Value = "Doomhammer"},
                new SelectListItem {Text = "Draenor", Value = "Draenor"},
                new SelectListItem {Text = "Dragonblight", Value = "Dragonblight"},
                new SelectListItem {Text = "Dragonmaw", Value = "Dragonmaw"},
                new SelectListItem {Text = "Drak'thul", Value = "Drak'thul"},
                new SelectListItem {Text = "Drek'Thar", Value = "Drek'Thar"},
                new SelectListItem {Text = "Dun Modr", Value = "Dun Modr"},
                new SelectListItem {Text = "Dun Morogh", Value = "Dun Morogh"},
                new SelectListItem {Text = "Dunemaul", Value = "Dunemaul"},
                new SelectListItem {Text = "Durotan", Value = "Durotan"},
                new SelectListItem {Text = "Earthen Ring", Value = "Earthen Ring"},
                new SelectListItem {Text = "Echsenkessel", Value = "Echsenkessel"},
                new SelectListItem {Text = "Eitrigg", Value = "Eitrigg"},
                new SelectListItem {Text = "Eldre'Thalas", Value = "Eldre'Thalas"},
                new SelectListItem {Text = "Elune", Value = "Elune"},
                new SelectListItem {Text = "Emerald Dream", Value = "Emerald Dream"},
                new SelectListItem {Text = "Emeriss", Value = "Emeriss"},
                new SelectListItem {Text = "Eonar", Value = "Eonar"},
                new SelectListItem {Text = "Eredar", Value = "Eredar"},
                new SelectListItem {Text = "Eversong", Value = "Eversong"},
                new SelectListItem {Text = "Executus", Value = "Executus"},
                new SelectListItem {Text = "Exodar", Value = "Exodar"},
                new SelectListItem {Text = "Festung der Stürme", Value = "Festung der Stürme"},
                new SelectListItem {Text = "Fordragon", Value = "Fordragon"},
                new SelectListItem {Text = "Forscherliga", Value = "Forscherliga"},
                new SelectListItem {Text = "Frostmane", Value = "Frostmane"},
                new SelectListItem {Text = "Frostmourne", Value = "Frostmourne"},
                new SelectListItem {Text = "Frostwhisper", Value = "Frostwhisper"},
                new SelectListItem {Text = "Frostwolf", Value = "Frostwolf"},
                new SelectListItem {Text = "Galakrond", Value = "Galakrond"},
                new SelectListItem {Text = "Garona", Value = "Garona"},
                new SelectListItem {Text = "Garrosh", Value = "Garrosh"},
                new SelectListItem {Text = "Genjuros", Value = "Genjuros"},
                new SelectListItem {Text = "Ghostlands", Value = "Ghostlands"},
                new SelectListItem {Text = "Gilneas", Value = "Gilneas"},
                new SelectListItem {Text = "Goldrinn", Value = "Goldrinn"},
                new SelectListItem {Text = "Gordunni", Value = "Gordunni"},
                new SelectListItem {Text = "Gorgonnash", Value = "Gorgonnash"},
                new SelectListItem {Text = "Greymane", Value = "Greymane"},
                new SelectListItem {Text = "Grim Batol", Value = "Grim Batol"},
                new SelectListItem {Text = "Grom", Value = "Grom"},
                new SelectListItem {Text = "Gul'dan", Value = "Gul'dan"},
                new SelectListItem {Text = "Hakkar", Value = "Hakkar"},
                new SelectListItem {Text = "Haomarush", Value = "Haomarush"},
                new SelectListItem {Text = "Hellfire", Value = "Hellfire"},
                new SelectListItem {Text = "Hellscream", Value = "Hellscream"},
                new SelectListItem {Text = "Howling Fjord", Value = "Howling Fjord"},
                new SelectListItem {Text = "Hyjal", Value = "Hyjal"},
                new SelectListItem {Text = "Illidan", Value = "Illidan"},
                new SelectListItem {Text = "Jaedenar", Value = "Jaedenar"},
                new SelectListItem {Text = "Kael'thas", Value = "Kael'thas"},
                new SelectListItem {Text = "Karazhan", Value = "Karazhan"},
                new SelectListItem {Text = "Kargath", Value = "Kargath"},
                new SelectListItem {Text = "Kazzak", Value = "Kazzak"},
                new SelectListItem {Text = "Kel'Thuzad", Value = "Kel'Thuzad"},
                new SelectListItem {Text = "Khadgar", Value = "Khadgar"},
                new SelectListItem {Text = "Khaz Modan", Value = "Khaz Modan"},
                new SelectListItem {Text = "Khaz'goroth", Value = "Khaz'goroth"},
                new SelectListItem {Text = "Kil'jaeden", Value = "Kil'jaeden"},
                new SelectListItem {Text = "Kilrogg", Value = "Kilrogg"},
                new SelectListItem {Text = "Kirin Tor", Value = "Kirin Tor"},
                new SelectListItem {Text = "Kor'gall", Value = "Kor'gall"},
                new SelectListItem {Text = "Krag'jin", Value = "Krag'jin"},
                new SelectListItem {Text = "Krasus", Value = "Krasus"},
                new SelectListItem {Text = "Kul Tiras", Value = "Kul Tiras"},
                new SelectListItem {Text = "Kult der Verdammten", Value = "Kult der Verdammten"},
                new SelectListItem {Text = "La Croisade écarlate", Value = "La Croisade écarlate"},
                new SelectListItem {Text = "Laughing Skull", Value = "Laughing Skull"},
                new SelectListItem {Text = "Les Clairvoyants", Value = "Les Clairvoyants"},
                new SelectListItem {Text = "Les Sentinelles", Value = "Les Sentinelles"},
                new SelectListItem {Text = "Lich King", Value = "Lich King"},
                new SelectListItem {Text = "Lightbringer", Value = "Lightbringer"},
                new SelectListItem {Text = "Lightning's Blade", Value = "Lightning's Blade"},
                new SelectListItem {Text = "Lordaeron", Value = "Lordaeron"},
                new SelectListItem {Text = "Los Errantes", Value = "Los Errantes"},
                new SelectListItem {Text = "Lothar", Value = "Lothar"},
                new SelectListItem {Text = "Madmortem", Value = "Madmortem"},
                new SelectListItem {Text = "Magtheridon", Value = "Magtheridon"},
                new SelectListItem {Text = "Mal'Ganis", Value = "Mal'Ganis"},
                new SelectListItem {Text = "Malfurion", Value = "Malfurion"},
                new SelectListItem {Text = "Malorne", Value = "Malorne"},
                new SelectListItem {Text = "Malygos", Value = "Malygos"},
                new SelectListItem {Text = "Mannoroth", Value = "Mannoroth"},
                new SelectListItem {Text = "Marécage de Zangar", Value = "Marécage de Zangar"},
                new SelectListItem {Text = "Mazrigos", Value = "Mazrigos"},
                new SelectListItem {Text = "Medivh", Value = "Medivh"},
                new SelectListItem {Text = "Minahonda", Value = "Minahonda"},
                new SelectListItem {Text = "Moonglade", Value = "Moonglade"},
                new SelectListItem {Text = "Mug'thol", Value = "Mug'thol"},
                new SelectListItem {Text = "Nagrand", Value = "Nagrand"},
                new SelectListItem {Text = "Nathrezim", Value = "Nathrezim"},
                new SelectListItem {Text = "Naxxramas", Value = "Naxxramas"},
                new SelectListItem {Text = "Nazjatar", Value = "Nazjatar"},
                new SelectListItem {Text = "Nefarian", Value = "Nefarian"},
                new SelectListItem {Text = "Nemesis", Value = "Nemesis"},
                new SelectListItem {Text = "Neptulon", Value = "Neptulon"},
                new SelectListItem {Text = "Ner'zhul", Value = "Ner'zhul"},
                new SelectListItem {Text = "Nera'thor", Value = "Nera'thor"},
                new SelectListItem {Text = "Nethersturm", Value = "Nethersturm"},
                new SelectListItem {Text = "Nordrassil", Value = "Nordrassil"},
                new SelectListItem {Text = "Norgannon", Value = "Norgannon"},
                new SelectListItem {Text = "Nozdormu", Value = "Nozdormu"},
                new SelectListItem {Text = "Onyxia", Value = "Onyxia"},
                new SelectListItem {Text = "Outland", Value = "Outland"},
                new SelectListItem {Text = "Perenolde", Value = "Perenolde"},
                new SelectListItem {Text = "Pozzo dell'Eternità", Value = "Pozzo dell'Eternità"},
                new SelectListItem {Text = "Proudmoore", Value = "Proudmoore"},
                new SelectListItem {Text = "Quel'Thalas", Value = "Quel'Thalas"},
                new SelectListItem {Text = "Ragnaros", Value = "Ragnaros"},
                new SelectListItem {Text = "Rajaxx", Value = "Rajaxx"},
                new SelectListItem {Text = "Rashgarroth", Value = "Rashgarroth"},
                new SelectListItem {Text = "Ravencrest", Value = "Ravencrest"},
                new SelectListItem {Text = "Ravenholdt", Value = "Ravenholdt"},
                new SelectListItem {Text = "Razuvious", Value = "Razuvious"},
                new SelectListItem {Text = "Rexxar", Value = "Rexxar"},
                new SelectListItem {Text = "Runetotem", Value = "Runetotem"},
                new SelectListItem {Text = "Sanguino", Value = "Sanguino"},
                new SelectListItem {Text = "Sargeras", Value = "Sargeras"},
                new SelectListItem {Text = "Saurfang", Value = "Saurfang"},
                new SelectListItem {Text = "Scarshield Legion", Value = "Scarshield Legion"},
                new SelectListItem {Text = "Sen'jin", Value = "Sen'jin"},
                new SelectListItem {Text = "Shadowsong", Value = "Shadowsong"},
                new SelectListItem {Text = "Shattered Halls", Value = "Shattered Halls"},
                new SelectListItem {Text = "Shattered Hand", Value = "Shattered Hand"},
                new SelectListItem {Text = "Shattrath", Value = "Shattrath"},
                new SelectListItem {Text = "Shen'dralar", Value = "Shen'dralar"},
                new SelectListItem {Text = "Silvermoon", Value = "Silvermoon"},
                new SelectListItem {Text = "Sinstralis", Value = "Sinstralis"},
                new SelectListItem {Text = "Skullcrusher", Value = "Skullcrusher"},
                new SelectListItem {Text = "Soulflayer", Value = "Soulflayer"},
                new SelectListItem {Text = "Spinebreaker", Value = "Spinebreaker"},
                new SelectListItem {Text = "Sporeggar", Value = "Sporeggar"},
                new SelectListItem {Text = "Steamwheedle Cartel", Value = "Steamwheedle Cartel"},
                new SelectListItem {Text = "Stormrage", Value = "Stormrage"},
                new SelectListItem {Text = "Stormreaver", Value = "Stormreaver"},
                new SelectListItem {Text = "Stormscale", Value = "Stormscale"},
                new SelectListItem {Text = "Sunstrider", Value = "Sunstrider"},
                new SelectListItem {Text = "Suramar", Value = "Suramar"},
                new SelectListItem {Text = "Sylvanas", Value = "Sylvanas"},
                new SelectListItem {Text = "Taerar", Value = "Taerar"},
                new SelectListItem {Text = "Talnivarr", Value = "Talnivarr"},
                new SelectListItem {Text = "Tarren Mill", Value = "Tarren Mill"},
                new SelectListItem {Text = "Teldrassil", Value = "Teldrassil"},
                new SelectListItem {Text = "Temple noir", Value = "Temple noir"},
                new SelectListItem {Text = "Terenas", Value = "Terenas"},
                new SelectListItem {Text = "Terokkar", Value = "Terokkar"},
                new SelectListItem {Text = "Terrordar", Value = "Terrordar"},
                new SelectListItem {Text = "The Maelstrom", Value = "The Maelstrom"},
                new SelectListItem {Text = "The Sha'tar", Value = "The Sha'tar"},
                new SelectListItem {Text = "The Venture Co", Value = "The Venture Co"},
                new SelectListItem {Text = "Theradras", Value = "Theradras"},
                new SelectListItem {Text = "Thermaplugg", Value = "Thermaplugg"},
                new SelectListItem {Text = "Thrall", Value = "Thrall"},
                new SelectListItem {Text = "Throk'Feroth", Value = "Throk'Feroth"},
                new SelectListItem {Text = "Thunderhorn", Value = "Thunderhorn"},
                new SelectListItem {Text = "Tichondrius", Value = "Tichondrius"},
                new SelectListItem {Text = "Tirion", Value = "Tirion"},
                new SelectListItem {Text = "Todeswache", Value = "Todeswache"},
                new SelectListItem {Text = "Trollbane", Value = "Trollbane"},
                new SelectListItem {Text = "Turalyon", Value = "Turalyon"},
                new SelectListItem {Text = "Twilight's Hammer", Value = "Twilight's Hammer"},
                new SelectListItem {Text = "Twisting Nether", Value = "Twisting Nether"},
                new SelectListItem {Text = "Tyrande", Value = "Tyrande"},
                new SelectListItem {Text = "Uldaman", Value = "Uldaman"},
                new SelectListItem {Text = "Ulduar", Value = "Ulduar"},
                new SelectListItem {Text = "Uldum", Value = "Uldum"},
                new SelectListItem {Text = "Un'Goro", Value = "Un'Goro"},
                new SelectListItem {Text = "Varimathras", Value = "Varimathras"},
                new SelectListItem {Text = "Vashj", Value = "Vashj"},
                new SelectListItem {Text = "Vek'lor", Value = "Vek'lor"},
                new SelectListItem {Text = "Vek'nilash", Value = "Vek'nilash"},
                new SelectListItem {Text = "Vol'jin", Value = "Vol'jin"},
                new SelectListItem {Text = "Wildhammer", Value = "Wildhammer"},
                new SelectListItem {Text = "Wrathbringer", Value = "Wrathbringer"},
                new SelectListItem {Text = "Xavius", Value = "Xavius"},
                new SelectListItem {Text = "Ysera", Value = "Ysera"},
                new SelectListItem {Text = "Ysondre", Value = "Ysondre"},
                new SelectListItem {Text = "Zenedar", Value = "Zenedar"},
                new SelectListItem {Text = "Zirkel des Cenarius", Value = "Zirkel des Cenarius"},
                new SelectListItem {Text = "Zul'jin", Value = "Zul'jin"},
                new SelectListItem {Text = "Zuluhed", Value = "Zuluhed"}

            };
        }

        public List<SelectListItem> RealmNames { get; set; }
    }
}