// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoWJunkyard.Data;

namespace WoWJunkyard.Data.Migrations
{
    [DbContext(typeof(WoWDbContext))]
    [Migration("20190812161527_UpdateNewsModel")]
    partial class UpdateNewsModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("ProviderKey");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.HasKey("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.AzeriteEmpoweredItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("AzeriteEmpoweredItems");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.AzeriteItem", b =>
                {
                    b.Property<long>("AzeriteItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AzeriteExperience");

                    b.Property<long>("AzeriteExperienceRemaining");

                    b.Property<long>("AzeriteLevel");

                    b.Property<long>("Id");

                    b.HasKey("AzeriteItemId");

                    b.ToTable("AzeriteItems");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.AzeritePower", b =>
                {
                    b.Property<int>("AzeritePowerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BonusListId");

                    b.Property<long>("Id");

                    b.Property<long>("SpellId");

                    b.Property<long>("Tier");

                    b.HasKey("AzeritePowerId");

                    b.HasIndex("Id");

                    b.ToTable("AzeritePowers");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AchievementPoints");

                    b.Property<long>("Class");

                    b.Property<long>("Faction");

                    b.Property<int>("ItemsId");

                    b.Property<long>("LastModified");

                    b.Property<long>("Level");

                    b.Property<string>("Name");

                    b.Property<long>("Race");

                    b.Property<string>("Realm");

                    b.Property<string>("Thumbnail");

                    b.Property<string>("WoWAccountId");

                    b.HasKey("Id");

                    b.HasIndex("ItemsId");

                    b.HasIndex("WoWAccountId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Damage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ExactMax");

                    b.Property<long>("ExactMin");

                    b.Property<long>("Max");

                    b.Property<long>("Min");

                    b.HasKey("Id");

                    b.ToTable("Damages");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Dungeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccomplishedLevel");

                    b.Property<int?>("CharacterId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.ItemInfo", b =>
                {
                    b.Property<long>("ItemInfoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Armor");

                    b.Property<long>("ArtifactAppearanceId");

                    b.Property<long>("ArtifactId");

                    b.Property<long>("AzeriteEmpoweredItemId");

                    b.Property<long>("AzeriteItemId");

                    b.Property<string>("BonusLists");

                    b.Property<string>("Context");

                    b.Property<long>("DisplayInfoId");

                    b.Property<string>("Icon");

                    b.Property<long>("Id");

                    b.Property<long>("ItemLevel");

                    b.Property<int>("ItemsId");

                    b.Property<string>("Name");

                    b.Property<long>("Quality");

                    b.HasKey("ItemInfoId");

                    b.HasIndex("AzeriteEmpoweredItemId");

                    b.HasIndex("AzeriteItemId");

                    b.HasIndex("ItemsId");

                    b.ToTable("ItemInfos");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AverageItemLevel");

                    b.Property<long>("AverageItemLevelEquipped");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Stat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Amount");

                    b.Property<long?>("ItemInfoId");

                    b.Property<long>("StatStat");

                    b.HasKey("Id");

                    b.HasIndex("ItemInfoId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.WeaponInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DamageId");

                    b.Property<double>("Dps");

                    b.Property<double>("WeaponSpeed");

                    b.HasKey("Id");

                    b.HasIndex("DamageId");

                    b.ToTable("WeaponInfos");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.WoWAccount", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsVerified");

                    b.Property<string>("Realm");

                    b.Property<string>("Region");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("WoWAccounts");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.WoWUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("AccountId");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("WoWUser");
                });

            modelBuilder.Entity("WoWJunkyard.Models.News.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Image");

                    b.Property<DateTime>("PostedOn");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.AzeritePower", b =>
                {
                    b.HasOne("WoWJunkyard.Data.Models.AzeriteEmpoweredItem")
                        .WithMany("AzeritePowers")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Character", b =>
                {
                    b.HasOne("WoWJunkyard.Data.Models.Items", "Items")
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WoWJunkyard.Data.Models.WoWAccount")
                        .WithMany("Characters")
                        .HasForeignKey("WoWAccountId");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Dungeon", b =>
                {
                    b.HasOne("WoWJunkyard.Data.Models.Character")
                        .WithMany("Dungeons")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.ItemInfo", b =>
                {
                    b.HasOne("WoWJunkyard.Data.Models.AzeriteEmpoweredItem", "AzeriteEmpoweredItem")
                        .WithMany()
                        .HasForeignKey("AzeriteEmpoweredItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WoWJunkyard.Data.Models.AzeriteItem", "AzeriteItem")
                        .WithMany()
                        .HasForeignKey("AzeriteItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WoWJunkyard.Data.Models.Items", "Items")
                        .WithMany("ItemInfos")
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.Stat", b =>
                {
                    b.HasOne("WoWJunkyard.Data.Models.ItemInfo")
                        .WithMany("Stats")
                        .HasForeignKey("ItemInfoId");
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.WeaponInfo", b =>
                {
                    b.HasOne("WoWJunkyard.Data.Models.Damage", "Damage")
                        .WithMany()
                        .HasForeignKey("DamageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WoWJunkyard.Data.Models.WoWUser", b =>
                {
                    b.HasOne("WoWJunkyard.Data.Models.WoWAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
